// export const dummy = [
//   {
//     hospitalNo: 1195,
//     hospitalPartner: true,
//     x: 37.6242919967,
//     rdnwhladdr:
//       "경기도 남양주시 다산중앙로123번길 22-8, 리더스퀘어 303,304호 (다산동)",
//     trdstatenm: "정상",
//     sitetel: "031-522-6675", // 2
//     bplcnm: "스텔라동물의료센터", // 1
//     y: 127.151045135,
//   },
//   {
//     hospitalNo: 1196,
//     hospitalPartner: true,
//     x: 37.34004829,
//     rdnwhladdr:
//       "경기도 성남시 분당구 성남대로 45, 계영빌딩 202, 203호 (구미동)",
//     trdstatenm: "정상",
//     sitetel: "031-711-8275",
//     bplcnm: "24시분당리더스동물의료원",
//     y: 127.1084036802,
//   },
//   {
//     hospitalNo: 1197,
//     hospitalPartner: true,
//     x: 37.4414927051,
//     rdnwhladdr: "경기도 성남시 수정구 수정로 130, 창도빌딩 2층 (수진동)",
//     trdstatenm: "정상",
//     sitetel: "031-757-2475",
//     bplcnm: "미래동물의료센터 성남점",
//     y: 127.1347919138,
//   },
//   {
//     hospitalNo: 1198,
//     hospitalPartner: false,
//     x: "37.441279994",
//     rdnwhladdr: "경기도 성남시 중원구 희망로 402, 지하1층 (금광동)",
//     trdstatenm: "정상",
//     sitetel: "031-747-0406",
//     bplcnm: "해오름동물병원",
//     y: "127.1601830448",
//   },
//   {
//     hospitalNo: 1199,
//     hospitalPartner: true,
//     x: 37.2748505809,
//     rdnwhladdr: "경기도 수원시 권선구 금곡로 213, 203,204,309호 (금곡동)",
//     trdstatenm: "정상",
//     sitetel: "031-291-2475",
//     bplcnm: "수원24시 바른동물의료센터",
//     y: 126.9536470852,
//   },
//   {
//     hospitalNo: 1200,
//     hospitalPartner: false,
//     x: 37.7200831558,
//     rdnwhladdr: "경기도 남양주시 진접읍 해밀예당1로 220, 엠타워 201호",
//     trdstatenm: "정상",
//     sitetel: "031-575-8275",
//     bplcnm: "24시 공감365동물의료센터",
//     y: 127.2026214866,
//   },
//   {
//     hospitalNo: 1201,
//     hospitalPartner: true,
//     x: 37.5020280866,
//     rdnwhladdr:
//       "경기도 부천시 소향로 181, 상가동 1층 125호 (중동, 센트럴파크 푸르지오)",
//     trdstatenm: "정상",
//     sitetel: "032-724-9898",
//     bplcnm: "중동우리아이동물병원",
//     y: 126.7679235986,
//   },
//   {
//     hospitalNo: 1202,
//     hospitalPartner: false,
//     x: 37.2088181193,
//     rdnwhladdr: "경기도 화성시 동탄지성로 112, 1층 (반송동)",
//     trdstatenm: "정상",
//     sitetel: "03180033232",
//     bplcnm: "S동물의료센터",
//     y: 127.0631471626,
//   },
// ];

export const dummy = [
  {
    chatroomNo: 1,
    sender: {
      userId: "ckdrua12",
      userPass: "",
      userName: "주용준",
      userAge: null,
      userAddress: null,
      userSex: null,
      userCard: null,
      userCardpass: null,
      userImg: null,
      userLicence: "",
      userUpdateTime: null,
    },
    receiver: {
      userId: "ckdrua76",
      userPass: "",
      userName: "김창겸",
      userAge: null,
      userAddress: null,
      userSex: null,
      userCard: null,
      userCardpass: null,
      userImg: null,
      userLicence: "",
      userUpdateTime: null,
    },
  },
  {
    chatroomNo: 2,
    sender: {
      userId: "ckdrua12",
      userPass: "",
      userName: "주용준",
      userAge: null,
      userAddress: null,
      userSex: null,
      userCard: null,
      userCardpass: null,
      userImg: null,
      userLicence: "",
      userUpdateTime: null,
    },
    receiver: {
      userId: "ckdrua34",
      userPass: "",
      userName: "강태영",
      userAge: null,
      userAddress: null,
      userSex: null,
      userCard: null,
      userCardpass: null,
      userImg: null,
      userLicence: "",
      userUpdateTime: null,
    },
  },
  {
    chatroomNo: 3,
    sender: {
      userId: "ckdrua56",
      userPass: "",
      userName: "유지만",
      userAge: null,
      userAddress: null,
      userSex: null,
      userCard: null,
      userCardpass: null,
      userImg: null,
      userLicence: "",
      userUpdateTime: null,
    },
    receiver: {
      userId: "ckdrua12",
      userPass: "",
      userName: "주용준",
      userAge: null,
      userAddress: null,
      userSex: null,
      userCard: null,
      userCardpass: null,
      userImg: null,
      userLicence: "",
      userUpdateTime: null,
    },
  },
  {
    chatroomNo: 4,
    sender: {
      userId: "ckdrua12",
      userPass: "",
      userName: "주용준",
      userAge: null,
      userAddress: null,
      userSex: null,
      userCard: null,
      userCardpass: null,
      userImg: null,
      userLicence: "",
      userUpdateTime: null,
    },
    receiver: {
      userId: "ckdrua11",
      userPass: "",
      userName: "이찬혁",
      userAge: null,
      userAddress: null,
      userSex: null,
      userCard: null,
      userCardpass: null,
      userImg: null,
      userLicence: "",
      userUpdateTime: null,
    },
  },
  {
    chatroomNo: 5,
    sender: {
      userId: "ckdrua12",
      userPass: "",
      userName: "주용준",
      userAge: null,
      userAddress: null,
      userSex: null,
      userCard: null,
      userCardpass: null,
      userImg: null,
      userLicence: "",
      userUpdateTime: null,
    },
    receiver: {
      userId: "ckdrua22",
      userPass: "",
      userName: "전은정",
      userAge: null,
      userAddress: null,
      userSex: null,
      userCard: null,
      userCardpass: null,
      userImg: null,
      userLicence: "",
      userUpdateTime: null,
    },
  },
];
